/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/utqhsTpTzM5
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Inter } from 'next/font/google'

 inter({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import {Dialog, DialogTrigger, DialogContent, DialogTitle} from "@/components/ui/dialog"
import {Button} from "@/components/ui/button"
import {VehicleData} from "@/hooks/useVehicle";

interface AlertBoxProps {
    createTrip: () => void
    trip: {
        departure: string,
        arrival: string,
        distance: string,
        duration: string,
        trips: any[],
        model: string | null,
        user?: string | null,
        userId?: string | null,
        startDate?: string | null,
    }
}

export function AlertBoxCreatedTrip(props: AlertBoxProps) {
    return (
        <Dialog defaultOpen>
            <DialogContent className="sm:max-w-[425px] bg-white">
                <div className="flex flex-col items-center justify-center gap-6 py-8">
                    <div className="space-y-2 text-center">
                        <DialogTitle className="text-2xl font-bold">En route !</DialogTitle>
                        <p className="text-muted-foreground">Votre trajet à été créé avec succès !</p>
                    </div>
                    <div className="flex w-full justify-center gap-4">
                        <Button onClick={() => props.createTrip()}>Continuer</Button>
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    )
}
