/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Dot2toYsY84
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {CardTitle, CardHeader, CardContent, CardFooter, Card} from "@/components/ui/card"
import {Input} from "@/components/ui/input"
import {Button} from "@/components/ui/button"
import {ScrollArea} from "@/components/ui/scroll-area"
import {Avatar, AvatarFallback, AvatarImage} from "@/components/ui/avatar"

export function HomeCards() {
    return (
        <div className="flex flex-col gap-8 p-4 bg-gray-100 sm:flex-row sm:p-8">
            <Card className="w-full sm:w-[350px]">
                <CardHeader>
                    <CardTitle>Où allez-vous aujourd&apos;hui ?</CardTitle>
                </CardHeader>
                <CardContent>
                    <div className="space-y-4">
                        <div className="flex items-center space-x-2">
                            <MapPinIcon className="h-5 w-5 text-gray-400"/>
                            <Input placeholder="Ville de départ"/>
                        </div>
                        <div className="flex items-center space-x-2">
                            <MapPinIcon className="h-5 w-5 text-gray-400"/>
                            <Input placeholder="Ville d'arrivée"/>
                        </div>
                        <div className="flex items-center space-x-2">
                            <CalendarDaysIcon className="h-5 w-5 text-gray-400"/>
                            <Input placeholder="Mardi 10 octobre"/>
                        </div>
                        <Button className="justify-start text-blue-600" variant="ghost">
                            Ajouter un retour
                        </Button>
                        <div className="flex items-center space-x-2">
                            <UserIcon className="h-5 w-5 text-gray-400"/>
                            <Input placeholder="1 passager(ère)"/>
                        </div>
                    </div>
                </CardContent>
                <CardFooter>
                    <Button className="w-full">Gooo !!!</Button>
                </CardFooter>
            </Card>
            <Card className="w-full sm:w-[350px]">
                <CardHeader>
                    <CardTitle>On vous propose !</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                    <ScrollArea className="space-y-4">
                        {[...Array(5)].map((_, i) => (
                            <div key={i} className="flex items-center space-x-4">
                                <Avatar>
                                    <AvatarImage src="https://api.multiavatar.com/ecovoit.png" />
                                    <AvatarFallback>Em</AvatarFallback>
                                </Avatar>
                                <div className="flex-grow">
                                    <div className="flex items-center space-x-2 font-semibold">
                                        <MapPinIcon className="h-4 w-4 text-gray-400"/>
                                        <div>Avignon</div>
                                    </div>
                                    <div className="text-sm text-gray-500">
                                        <div className="flex items-center space-x-2">
                                            <ClockIcon className="h-4 w-4"/>
                                            <div>Depart: 8h00</div>
                                        </div>
                                    </div>
                                    <div className="flex items-center space-x-2 font-semibold">
                                        <MapPinIcon className="h-4 w-4 text-gray-400"/>
                                        <div>Nextech</div>
                                    </div>
                                    <div className="text-sm text-gray-500">
                                        <div className="flex items-center space-x-2">
                                            <ClockIcon className="h-4 w-4"/>
                                            <div>Arrivé: 8h25</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </ScrollArea>
                </CardContent>
                <CardFooter>
                    <Button className="w-full">Sélectionner</Button>
                </CardFooter>
            </Card>
        </div>
    )
}

// @ts-ignore
function CalendarDaysIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M8 2v4"/>
            <path d="M16 2v4"/>
            <rect width="18" height="18" x="3" y="4" rx="2"/>
            <path d="M3 10h18"/>
            <path d="M8 14h.01"/>
            <path d="M12 14h.01"/>
            <path d="M16 14h.01"/>
            <path d="M8 18h.01"/>
            <path d="M12 18h.01"/>
            <path d="M16 18h.01"/>
        </svg>
    )
}


// @ts-ignore
function MapPinIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/>
            <circle cx="12" cy="10" r="3"/>
        </svg>
    )
}

// @ts-ignore
function ClockIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="12" cy="12" r="10"/>
            <polyline points="12 6 12 12 16 14"/>
        </svg>
    )
}


// @ts-ignore
function UserIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/>
            <circle cx="12" cy="7" r="4"/>
        </svg>
    )
}
