/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TLu0Sxk1Zjk
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Libre_Franklin } from 'next/font/google'
 import { Judson } from 'next/font/google'

 libre_franklin({
 subsets: ['latin'],
 display: 'swap',
 })

 judson({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import Link from "next/link"

export function Landing() {
    return (
        <div className="flex flex-col min-h-[100dvh]">
            <main className="flex-1">
                <section className="w-full pt-12 md:pt-24 lg:pt-32">
                    <div className="container px-4 md:px-6 space-y-10 xl:space-y-16">
                        <div
                            className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
                            <div>
                                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                                    Simplify Your Commute with Carpool App
                                </h1>
                                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                                    Reduce your carbon footprint, save money, and connect with your community through
                                    our easy-to-use
                                    carpooling platform.
                                </p>
                                <div className="space-x-4 mt-6">
                                    <Link
                                        className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                                        href="#"
                                    >
                                        Join Now
                                    </Link>
                                </div>
                            </div>
                            <div>
                                <img
                                    alt="Hero"
                                    className="mx-auto aspect-[3/1] overflow-hidden rounded-t-xl object-cover"
                                    height="300"
                                    src="/placeholder.svg"
                                    width="1270"
                                />
                            </div>
                        </div>
                    </div>
                </section>
                <section className="w-full py-12 md:py-24 lg:py-32">
                    <div className="container space-y-12 px-4 md:px-6">
                        <div className="flex flex-col items-center justify-center space-y-4 text-center">
                            <div className="space-y-2">
                                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Why Choose Carpool
                                    App?</h2>
                                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                    Our carpooling platform offers a range of benefits to help you save time, money, and
                                    the environment.
                                </p>
                            </div>
                        </div>
                        <div
                            className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
                            <div className="grid gap-1">
                                <WalletIcon className="h-8 w-8 text-gray-900 dark:text-gray-50"/>
                                <h3 className="text-lg font-bold">Save Money</h3>
                                <p className="text-sm text-gray-500 dark:text-gray-400">
                                    Reduce your commuting costs by sharing rides with others going the same way.
                                </p>
                            </div>
                            <div className="grid gap-1">
                                <TreesIcon className="h-8 w-8 text-gray-900 dark:text-gray-50"/>
                                <h3 className="text-lg font-bold">Reduce Emissions</h3>
                                <p className="text-sm text-gray-500 dark:text-gray-400">
                                    Help the environment by lowering your carbon footprint through carpooling.
                                </p>
                            </div>
                            <div className="grid gap-1">
                                <UsersIcon className="h-8 w-8 text-gray-900 dark:text-gray-50"/>
                                <h3 className="text-lg font-bold">Build Community</h3>
                                <p className="text-sm text-gray-500 dark:text-gray-400">
                                    Connect with your neighbors and colleagues by sharing rides and making new
                                    connections.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
                    <div
                        className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
                        <div className="space-y-3">
                            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">What Our Users
                                Say</h2>
                            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                Hear from real people who have used our carpooling app to improve their commute.
                            </p>
                        </div>
                        <div className="divide-y rounded-lg border">
                            <div
                                className="grid w-full grid-cols-3 items-stretch justify-center divide-x md:grid-cols-3">
                                <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                                    <div className="space-y-2 text-center">
                                        <img
                                            alt="Avatar"
                                            className="mx-auto rounded-full"
                                            height="60"
                                            src="/placeholder.svg"
                                            style={{
                                                aspectRatio: "60/60",
                                                objectFit: "cover",
                                            }}
                                            width="60"
                                        />
                                        <div className="font-semibold">Jane Doe</div>
                                        <div className="text-sm text-gray-500 dark:text-gray-400">
                                            Carpool App has been a game-changer for my daily commute. I&apos;ve saved so
                                            much money and made new
                                            friends.
                                        </div>
                                    </div>
                                </div>
                                <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                                    <div className="space-y-2 text-center">
                                        <img
                                            alt="Avatar"
                                            className="mx-auto rounded-full"
                                            height="60"
                                            src="/placeholder.svg"
                                            style={{
                                                aspectRatio: "60/60",
                                                objectFit: "cover",
                                            }}
                                            width="60"
                                        />
                                        <div className="font-semibold">John Smith</div>
                                        <div className="text-sm text-gray-500 dark:text-gray-400">
                                            I was hesitant at first, but Carpool App has made my commute so much more
                                            enjoyable. Highly
                                            recommended!
                                        </div>
                                    </div>
                                </div>
                                <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                                    <div className="space-y-2 text-center">
                                        <img
                                            alt="Avatar"
                                            className="mx-auto rounded-full"
                                            height="60"
                                            src="/placeholder.svg"
                                            style={{
                                                aspectRatio: "60/60",
                                                objectFit: "cover",
                                            }}
                                            width="60"
                                        />
                                        <div className="font-semibold">Sarah Lee</div>
                                        <div className="text-sm text-gray-500 dark:text-gray-400">
                                            Carpool App has been a lifesaver for me. I&apos;ve saved so much time and money,
                                            and it&apos;s been great
                                            meeting new people.
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div
                                className="grid w-full grid-cols-3 items-stretch justify-center divide-x md:grid-cols-3">
                                <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                                    <div className="space-y-2 text-center">
                                        <img
                                            alt="Avatar"
                                            className="mx-auto rounded-full"
                                            height="60"
                                            src="/placeholder.svg"
                                            style={{
                                                aspectRatio: "60/60",
                                                objectFit: "cover",
                                            }}
                                            width="60"
                                        />
                                        <div className="font-semibold">Michael Chen</div>
                                        <div className="text-sm text-gray-500 dark:text-gray-400">
                                            I was skeptical at first, but Carpool App has been a game-changer. It&apos;s so
                                            convenient and has
                                            saved me a ton of money.
                                        </div>
                                    </div>
                                </div>
                                <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                                    <div className="space-y-2 text-center">
                                        <img
                                            alt="Avatar"
                                            className="mx-auto rounded-full"
                                            height="60"
                                            src="/placeholder.svg"
                                            style={{
                                                aspectRatio: "60/60",
                                                objectFit: "cover",
                                            }}
                                            width="60"
                                        />
                                        <div className="font-semibold">Emily Wang</div>
                                        <div className="text-sm text-gray-500 dark:text-gray-400">
                                            I love using Carpool App. It&apos;s been a great way to connect with my
                                            community and reduce my carbon
                                            footprint.
                                        </div>
                                    </div>
                                </div>
                                <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                                    <div className="space-y-2 text-center">
                                        <img
                                            alt="Avatar"
                                            className="mx-auto rounded-full"
                                            height="60"
                                            src="/placeholder.svg"
                                            style={{
                                                aspectRatio: "60/60",
                                                objectFit: "cover",
                                            }}
                                            width="60"
                                        />
                                        <div className="font-semibold">David Lee</div>
                                        <div className="text-sm text-gray-500 dark:text-gray-400">
                                            Carpool App has been a game-changer for me. I&apos;ve saved so much time and
                                            money, and it&apos;s been
                                            great meeting new people.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
            <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
                <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Carpool App. All rights reserved.</p>
                <nav className="sm:ml-auto flex gap-4 sm:gap-6">
                    <Link className="text-xs hover:underline underline-offset-4" href="#">
                        Terms of Service
                    </Link>
                    <Link className="text-xs hover:underline underline-offset-4" href="#">
                        Privacy Policy
                    </Link>
                </nav>
            </footer>
        </div>
    )
}

// @ts-ignore
function TreesIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M10 10v.2A3 3 0 0 1 8.9 16v0H5v0h0a3 3 0 0 1-1-5.8V10a3 3 0 0 1 6 0Z"/>
            <path d="M7 16v6"/>
            <path d="M13 19v3"/>
            <path d="M12 19h8.3a1 1 0 0 0 .7-1.7L18 14h.3a1 1 0 0 0 .7-1.7L16 9h.2a1 1 0 0 0 .8-1.7L13 3l-1.4 1.5"/>
        </svg>
    )
}


// @ts-ignore
function UsersIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/>
            <circle cx="9" cy="7" r="4"/>
            <path d="M22 21v-2a4 4 0 0 0-3-3.87"/>
            <path d="M16 3.13a4 4 0 0 1 0 7.75"/>
        </svg>
    )
}


// @ts-ignore
function WalletIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path
                d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1"/>
            <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/>
        </svg>
    )
}
