/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vXD8ZSRBbtR
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Inter } from 'next/font/google'

 inter({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/

"use client";

import {Button} from "@/components/ui/button"
import {SheetTrigger, SheetClose, SheetContent, Sheet} from "@/components/ui/sheet"
import Link from "next/link"
import Image from "next/image";
import {redirect} from "next/navigation";
import {useRouter} from "next/navigation";
import { ProfileDropdown } from "@/components/component/profile-dropdown";

// @ts-ignore
export function Navbar({onLogout, isLoggedIn}) {

    const router = useRouter();

    const redirectToLogin = () => {
        router.push('/login');
    };

    return (
        <header
            className="flex h-16 w-full items-center justify-between bg-white px-4 shadow-sm dark:bg-gray-950 md:px-6">
            <Sheet>
                <SheetTrigger asChild>
                    <Button className="md:hidden" size="icon" variant="outline">
                        <MenuIcon className="h-6 w-6"/>
                        <span className="sr-only">Toggle navigation menu</span>
                    </Button>
                </SheetTrigger>
                <SheetContent className="w-[300px] bg-white shadow-lg dark:bg-gray-950" side="left">
                    <div className="flex h-16 items-center justify-between px-4">
                        <Link className="flex items-center gap-2 text-lg font-semibold" href="#">
                            <EcovoitLogo/>
                        </Link>
                        <SheetClose>
                            <XIcon className="h-6 w-6"/>
                        </SheetClose>
                    </div>
                    <nav className="grid gap-4 px-4 py-6">
                        {isLoggedIn ? (
                            <>
                                <Link
                                    className="flex items-center gap-2 text-sm font-medium transition-colors hover:text-gray-900 dark:hover:text-gray-50"
                                    href="#"
                                >
                                    <CalendarDaysIcon className="h-5 w-5"/>
                                    Reserver un trajet
                                </Link>
                                <Link
                                    className="flex items-center gap-2 text-sm font-medium transition-colors hover:text-gray-900 dark:hover:text-gray-50"
                                    href="#"
                                >
                                    <TargetIcon className="h-5 w-5"/>
                                    Mes trajets
                                </Link>
                                <Link
                                    className="flex items-center gap-2 text-sm font-medium transition-colors hover:text-gray-900 dark:hover:text-gray-50"
                                    href="#"
                                >
                                    <UsersIcon className="h-5 w-5"/>
                                    M&apos;e-co-voit
                                </Link>

                                <div className="flex items-center gap-2">
                                    <ProfileDropdown onLogout={onLogout} size="small"></ProfileDropdown>
                                </div>
                            </>
                        ) : (
                            <Button onClick={redirectToLogin}
                                    className="transition-colors hover:text-gray-900 dark:hover:text-gray-50">Connexion</Button>
                        )}
                    </nav>
                </SheetContent>
            </Sheet>
            <Link className="flex items-center gap-2 text-lg font-semibold" href="#">
                <EcovoitLogo/>
            </Link>
            <nav className="hidden items-center gap-6 text-sm font-medium md:flex">
                {isLoggedIn ? (
                    <>
                        <Link className="p-2 transition-colors rounded-xl border-2 border-cyan-500 bg-white text-gray-500 font-bold hover:text-black dark:bg-black dark:text-gray-500 dark:hover:bg-gray-50/90" href="#">
                            Reserver un trajet
                        </Link>
                        <Link className="p-2 transition-colors rounded-xl border-2 border-cyan-500 bg-white text-gray-500 font-bold hover:text-black dark:bg-black dark:text-gray-500 dark:hover:bg-gray-50/90" href="#">
                            Mes trajets
                        </Link>
                        <Link className="p-2 transition-colors rounded-xl border-2 border-cyan-500 bg-white text-gray-500 font-bold hover:text-black dark:bg-black dark:text-gray-500 dark:hover:bg-gray-50/90" href="#">
                            M&apos;e-co-voit
                        </Link>
                        <ProfileDropdown onLogout={onLogout}/>
                    </>
                ) : (
                    <Button onClick={redirectToLogin}
                            className="transition-colors hover:text-gray-900 dark:hover:text-gray-50">Connexion</Button>
                )}
            </nav>
        </header>
    )
}

// @ts-ignore
function CalendarDaysIcon(props) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M8 2v4" />
        <path d="M16 2v4" />
        <rect width="18" height="18" x="3" y="4" rx="2" />
        <path d="M3 10h18" />
        <path d="M8 14h.01" />
        <path d="M12 14h.01" />
        <path d="M16 14h.01" />
        <path d="M8 18h.01" />
        <path d="M12 18h.01" />
        <path d="M16 18h.01" />
      </svg>
    )
  }


// @ts-ignore
function TargetIcon(props) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <circle cx="12" cy="12" r="10" />
        <circle cx="12" cy="12" r="6" />
        <circle cx="12" cy="12" r="2" />
      </svg>
    )
  }


// @ts-ignore
function UsersIcon(props) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
        <circle cx="9" cy="7" r="4" />
        <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
        <path d="M16 3.13a4 4 0 0 1 0 7.75" />
      </svg>
    )
  }


// @ts-ignore
function MailIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <rect width="20" height="16" x="2" y="4" rx="2"/>
            <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/>
        </svg>
    )
}


// @ts-ignore
function MenuIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <line x1="4" x2="20" y1="12" y2="12"/>
            <line x1="4" x2="20" y1="6" y2="6"/>
            <line x1="4" x2="20" y1="18" y2="18"/>
        </svg>
    )
}


function EcovoitLogo() {
    return (
        <Image src={"/img/logo.png"} alt={"ecovoit logo"} width={50} height={50}/>
    )
}


// @ts-ignore
function XIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M18 6 6 18"/>
            <path d="m6 6 12 12"/>
        </svg>
    )
}
