/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EDWgALKDesg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import useUser from "@/hooks/useUser";

export function Profil() {

  const {userData} = useUser();

  return (
    <div className="flex flex-col items-center justify-center min-h-[100dvh] bg-gray-100 dark:bg-gray-900 p-6">
      <div className="w-full max-w-md bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
        <div className="flex flex-col items-center mb-6">
          <div className="relative w-32 h-32 mb-4">
            <img
              alt="Profile Avatar"
              className="rounded-full w-full h-full object-cover"
              height={128}
              src="/img/sticker2.jpg"
              style={{
                aspectRatio: "128/128",
                objectFit: "cover",
              }}
              width={128}
            />
            <div className="absolute bottom-0 right-0 bg-gray-900 dark:bg-gray-700 text-white rounded-full w-8 h-8 flex items-center justify-center cursor-pointer">
              <FilePenIcon className="w-5 h-5" />
            </div>
          </div>
          <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Edit Profile</h2>
        </div>
        <form className="space-y-4">
          <div>
            <Label className="block mb-1 text-gray-700 dark:text-gray-300" htmlFor="name">
              Nom
            </Label>
            <Input
              className="w-full px-4 py-2 rounded-md border border-gray-200 border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:border-gray-800"
              id="name"
              placeholder={userData?.last_name}
              type="text"
            />
          </div>
          <div>
            <Label className="block mb-1 text-gray-700 dark:text-gray-300" htmlFor="name">
              Prenom
            </Label>
            <Input
              className="w-full px-4 py-2 rounded-md border border-gray-200 border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:border-gray-800"
              id="name"
              placeholder={userData?.first_name}
              type="text"
            />
          </div>
          <div>
            <Label className="block mb-1 text-gray-700 dark:text-gray-300" htmlFor="email">
              Email
            </Label>
            <Input
              className="w-full px-4 py-2 rounded-md border border-gray-200 border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:border-gray-800"
              id="email"
              placeholder={userData?.email}
              type="email"
            />
          </div>
          <div>
            <Label className="block mb-1 text-gray-700 dark:text-gray-300" htmlFor="email">
              Telephone
            </Label>
            <Input
              className="w-full px-4 py-2 rounded-md border border-gray-200 border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:border-gray-800"
              id="email"
              placeholder={userData?.phone_number}
              type="email"
            />
          </div>
          
          <Button
            className="w-full bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"
            type="submit"
          >
            Modifier
          </Button>
        </form>
      </div>
    </div>
  )
}

// @ts-ignore
function FilePenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}
