/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vCSAMVwvYcX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Inter } from 'next/font/google'

 inter({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import {AvatarImage, AvatarFallback, Avatar} from "@/components/ui/avatar"
import {
    DropdownMenuTrigger,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuContent,
    DropdownMenu
} from "@/components/ui/dropdown-menu"
import useUser from "@/hooks/useUser";
import {useRouter} from "next/navigation";
import {TripIcon} from "@/components/icons/TripIcon";
import {MessageIcon} from "@/components/icons/MessageIcon";
import {VehicleIcon} from "@/components/icons/VehicleIcon";
import {LogOutIcon} from "@/components/icons/LogOutIcon";
import {SettingsIcon} from "@/components/icons/SettingsIcon";
import {User1Icon} from "@/components/icons/User1Icon";

interface ProfileDropdownProps {
    onLogout: () => void;
    size?: 'small' | 'normal'
}

export function ProfileDropdown({onLogout, size = 'normal'}: ProfileDropdownProps) {
    const router = useRouter();
    const avatarSizeClass = size === 'small' ? 'h-5 w-5' : 'h-10 w-10';
    const {userData} = useUser();


    const redirectToProfile = () => {
        router.push('./my-profile');
    };
    const redirectToMyTrips = () => {
        router.push('.//my-trips');
    };
    const redirectToMessages = () => {
        router.push('./messages');

    };

    return (
        <DropdownMenu>
            <DropdownMenuTrigger asChild className={"cursor-pointer"}>
                {userData?.avatar && (
                    <div className="flex items-center gap-2">
                        <Avatar className={`${avatarSizeClass}`}>
                            <AvatarImage alt="avatar" src={`${userData?.avatar}`}/>
                            <AvatarFallback>{userData?.first_name}</AvatarFallback>
                        </Avatar>
                        {size === 'small' && <p className="text-sm font-medium">Mon Profil</p>}
                    </div>
                )}
            </DropdownMenuTrigger>
            <DropdownMenuContent className="w-56 p-2">
                <div className="flex items-center gap-2">
                    <Avatar className="h-8 w-8">
                        <AvatarImage alt="avatar" src={`${userData?.avatar}`}/>
                        <AvatarFallback>{userData?.first_name}</AvatarFallback>
                    </Avatar>
                    <div className="flex flex-col">
                        <p className="text-sm font-medium">{userData?.first_name} {userData?.last_name}</p>
                        <p className="text-xs text-gray-500 dark:text-gray-400">{userData?.email}</p>
                    </div>
                </div>
                <DropdownMenuSeparator/>
                <DropdownMenuItem onClick={redirectToMyTrips} className={"cursor-pointer"}>
                    <VehicleIcon className="h-4 w-4 mr-2"/>
                    <span>Mes trajets</span>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={redirectToMessages} className={"cursor-pointer"}>
                    <MessageIcon className="h-4 w-4 mr-2"/>
                    <span>Mes messages</span>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={redirectToProfile} className={"cursor-pointer"}>
                    <SettingsIcon className="h-4 w-4 mr-2"/>
                    <span>Mon profil</span>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={onLogout} className={"cursor-pointer"}>
                    <LogOutIcon className="h-4 w-4 mr-2"/>
                    <span>Logout</span>
                </DropdownMenuItem>
            </DropdownMenuContent>
        </DropdownMenu>
    )
}
